name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: workspace-app-one
        AWS_ACCESS_KEY_ID: AKIA2U37CIIO37HE57EA
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'dist/rickandmorty'      # optional: defaults to entire repository